# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/middleman
image: python:latest

variables:
  S3_BUCKET: "loreleyamiti"
  CF_DISTID: "nocheinfügen!"

stages:
  - deploy

production:
  stage: deploy
  script:
  - apt-get update -yqqq
  - pip install awscli
  - aws s3 sync --sse --exclude ".git/*" --exclude ".gitlab-ci.yml" --delete ./ s3://$S3_BUCKET/ --acl public-read
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CF_DISTID --paths '/*'
  environment:
    name: production
  only:
  - master
